add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$golang\
$rust\
$python\
$lua\
$nodejs\
$docker_context\
$line_break\
$character"""

[aws]
disabled = true

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "ï˜ "
style = "purple"

[git_status]
style = "red"
conflicted = "ğŸ³"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
up_to_date = ""
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"

[golang]
symbol = "î˜§ "
style = "cyan"
format = ' [$symbol($version )]($style)'

[rust]
symbol = "ğŸ¦€ "
style = "red"
format = ' [$symbol($version )]($style)'

[python]
symbol = "ğŸ "
style = "yellow"
format = ' [$symbol$pyenv_prefix($version )($virtualenv )]($style)'

[lua]
symbol = "ğŸŒ™ "
style = "blue"
format = ' [$symbol($version )]($style)'

[nodejs]
symbol = "ğŸŸ¢ "
style = "green"
format = ' [$symbol($version )]($style)'

[docker_context]
symbol = "ğŸ³ "
style = "blue"
format = ' [$symbol$context]($style)'

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vimcmd_symbol = "[V](bold green)"
